name: "gobbs"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2024-06-27"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "47.98.236.201"
  port: 3306
  user: "root"
  password: "zcc20001001"
  dbname: "gobbs"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "47.98.236.201"
  port: 6379
  password: "zcc20001001"
  db: 0
  pool_size: 100